### ISSUE TITLE
README: macOS Build

### ISSUE THREAD

**Issue by takoyaro** [hjalmar/svelte-electron-boilerplate#1]
Documentation reads 

> NOTE: Currently only windows configured out of the box.

I've been building on macOS out-of-the-box without any extra configuration, I think the README should reflect that.

**Comment by hjalmar** [comment]
What I'm trying to say is that I've only customized the windows build outside of the default. The Linux and MacOS build will simply refer to electron-builders default, I assume, but currently I'm not able to test it out since I'm an only windows user. So for me that was the easiest solution to leave a note about it since I simply don't know how it builds on MacOS or Linux currently. 

Appreciate the heads up and I'll think about better wording it and make it clearer! 👍 

You can check out the build options here https://www.electron.build/configuration/configuration
